packages:
  - "demo"
  - "vue-demo"
  - "packages/core"
  - "packages/pm"
  - "packages/html"
  - "packages/markdown"
  - "packages/static-renderer"
  - "packages/react"
  - "packages/vue-3"
  - "packages/extensions"
  - "packages/ai-context"
  - "packages/extension-*"
  # Exclude packages that depend on missing external dependencies
  - "!packages/extension-emoji" # needs @blockslides/suggestion package
